package edu.uv.model.pojos;
// Generated 25/05/2014 11:11:21 AM by Hibernate Tools 3.6.0

import java.util.HashSet;
import java.util.Set;
import org.hibernate.validator.constraints.Length;
import org.hibernate.validator.constraints.NotBlank;

/**
 * Carrera generated by hbm2java
 */
public class Carrera  implements java.io.Serializable {


     private Integer idCarrera;
     @NotBlank(message="Este campo no puede contener solo espacios en blanco")
     @Length(min=5, max=60, message="La longitud de campo no es valida, use de 5 a 60 caracteres")
     private String nombreCarrera;
     private Set carreraAcademias = new HashSet(0);

    public Carrera() {
    }

	
    public Carrera(String nombreCarrera) {
        this.nombreCarrera = nombreCarrera;
    }
    public Carrera(String nombreCarrera, Set carreraAcademias) {
       this.nombreCarrera = nombreCarrera;
       this.carreraAcademias = carreraAcademias;
    }
   
    public Integer getIdCarrera() {
        return this.idCarrera;
    }
    
    public void setIdCarrera(Integer idCarrera) {
        this.idCarrera = idCarrera;
    }
    public String getNombreCarrera() {
        return this.nombreCarrera;
    }
    
    public void setNombreCarrera(String nombreCarrera) {
        this.nombreCarrera = nombreCarrera;
    }
    public Set getCarreraAcademias() {
        return this.carreraAcademias;
    }
    
    public void setCarreraAcademias(Set carreraAcademias) {
        this.carreraAcademias = carreraAcademias;
    }
}