package edu.uv.model.pojos;
// Generated 12/05/2014 09:41:03 AM by Hibernate Tools 3.6.0



/**
 * CarreraAcademia generated by hbm2java
 */
public class CarreraAcademia  implements java.io.Serializable {


     private int idCarreraAcademia;
     private Carrera carrera;
     private Academia academia;

    public CarreraAcademia() {
    }

    public CarreraAcademia(int idCarreraAcademia, Carrera carrera, Academia academia) {
       this.idCarreraAcademia = idCarreraAcademia;
       this.carrera = carrera;
       this.academia = academia;
    }
   
    public int getIdCarreraAcademia() {
        return this.idCarreraAcademia;
    }
    
    public void setIdCarreraAcademia(int idCarreraAcademia) {
        this.idCarreraAcademia = idCarreraAcademia;
    }
    public Carrera getCarrera() {
        return this.carrera;
    }
    
    public void setCarrera(Carrera carrera) {
        this.carrera = carrera;
    }
    public Academia getAcademia() {
        return this.academia;
    }
    
    public void setAcademia(Academia academia) {
        this.academia = academia;
    }




}


