package edu.uv.model.pojos;
// Generated 12/05/2014 09:41:03 AM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Carrera generated by hbm2java
 */
public class Carrera  implements java.io.Serializable {


     private Integer idCarrera;
     private String nombreCarrera;
     private Set carreraAcademias = new HashSet(0);

    public Carrera() {
    }

	
    public Carrera(String nombreCarrera) {
        this.nombreCarrera = nombreCarrera;
    }
    public Carrera(String nombreCarrera, Set carreraAcademias) {
       this.nombreCarrera = nombreCarrera;
       this.carreraAcademias = carreraAcademias;
    }
   
    public Integer getIdCarrera() {
        return this.idCarrera;
    }
    
    public void setIdCarrera(Integer idCarrera) {
        this.idCarrera = idCarrera;
    }
    public String getNombreCarrera() {
        return this.nombreCarrera;
    }
    
    public void setNombreCarrera(String nombreCarrera) {
        this.nombreCarrera = nombreCarrera;
    }
    public Set getCarreraAcademias() {
        return this.carreraAcademias;
    }
    
    public void setCarreraAcademias(Set carreraAcademias) {
        this.carreraAcademias = carreraAcademias;
    }




}


