package edu.uv.model.pojos;
// Generated 25/05/2014 11:11:21 AM by Hibernate Tools 3.6.0
import javax.validation.constraints.Max;
import javax.validation.constraints.Min;




/**
 * ExamenPregunta generated by hbm2java
 */
public class ExamenPregunta  implements java.io.Serializable {


     private Integer idExamenPregunta;
     private ExamenesGenerados examenesGenerados;
     private Pregunta pregunta;
     @Min(1)
     @Max(100)
     private Integer puntaje;

    public ExamenPregunta() {
    }

	
    public ExamenPregunta(ExamenesGenerados examenesGenerados, Pregunta pregunta) {
        this.examenesGenerados = examenesGenerados;
        this.pregunta = pregunta;
    }
    public ExamenPregunta(ExamenesGenerados examenesGenerados, Pregunta pregunta, Integer puntaje) {
       this.examenesGenerados = examenesGenerados;
       this.pregunta = pregunta;
       this.puntaje = puntaje;
    }
   
    public Integer getIdExamenPregunta() {
        return this.idExamenPregunta;
    }
    
    public void setIdExamenPregunta(Integer idExamenPregunta) {
        this.idExamenPregunta = idExamenPregunta;
    }
    public ExamenesGenerados getExamenesGenerados() {
        return this.examenesGenerados;
    }
    
    public void setExamenesGenerados(ExamenesGenerados examenesGenerados) {
        this.examenesGenerados = examenesGenerados;
    }
    public Pregunta getPregunta() {
        return this.pregunta;
    }
    
    public void setPregunta(Pregunta pregunta) {
        this.pregunta = pregunta;
    }
    public Integer getPuntaje() {
        return this.puntaje;
    }
    
    public void setPuntaje(Integer puntaje) {
        this.puntaje = puntaje;
    }




}


