package edu.uv.model.pojos;
// Generated 25/05/2014 11:11:21 AM by Hibernate Tools 3.6.0


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.validation.constraints.Max;
import javax.validation.constraints.Min;
import javax.validation.constraints.NotNull;
import org.hibernate.validator.constraints.Length;
import org.hibernate.validator.constraints.NotBlank;

/**
 * ExamenesGenerados generated by hbm2java
 */
public class ExamenesGenerados  implements java.io.Serializable {


     private Integer idexamenesGenerados;
     private ExperieciaEducativa experieciaEducativa;
     private Personal personal;
     @NotBlank(message="Este campo no puede contener solo espacios en blanco")
     @Length(min=5, max=60, message="La longitud de campo no es valida, use de 5 a 60 caracteres")
     private String periodo;
     @NotBlank(message="Este campo no puede contener solo espacios en blanco")
     private String tipoExamen;
     private Date fechaCreacion;
     @NotBlank(message="Este campo no puede contener solo espacios en blanco")
     @Length(min=5, max=80, message="La longitud de campo no es valida, use de 5 a 80 caracteres")
     private String descripcionExamen;
     @Min(1)
     @Max(100)
     private Integer porcTeoria;
     @Min(1)
     @Max(100)
     private Integer porcPractica;
      @NotNull(message="Este campo no puede estar vacío")
     @NotBlank(message="Este campo no puede contener solo espacios en blanco")
     private String estadoExamen;
     private Set examenPreguntas = new HashSet(0);

    public ExamenesGenerados() {
    }

	
    public ExamenesGenerados(String periodo, String tipoExamen, Date fechaCreacion, String estadoExamen) {
        this.periodo = periodo;
        this.tipoExamen = tipoExamen;
        this.fechaCreacion = fechaCreacion;
        this.estadoExamen = estadoExamen;
    }
    public ExamenesGenerados(ExperieciaEducativa experieciaEducativa, Personal personal, String periodo, String tipoExamen, Date fechaCreacion, String descripcionExamen, Integer porcTeoria, Integer porcPractica, String estadoExamen, Set examenPreguntas) {
       this.experieciaEducativa = experieciaEducativa;
       this.personal = personal;
       this.periodo = periodo;
       this.tipoExamen = tipoExamen;
       this.fechaCreacion = fechaCreacion;
       this.descripcionExamen = descripcionExamen;
       this.porcTeoria = porcTeoria;
       this.porcPractica = porcPractica;
       this.estadoExamen = estadoExamen;
       this.examenPreguntas = examenPreguntas;
    }
   
    public Integer getIdexamenesGenerados() {
        return this.idexamenesGenerados;
    }
    
    public void setIdexamenesGenerados(Integer idexamenesGenerados) {
        this.idexamenesGenerados = idexamenesGenerados;
    }
    public ExperieciaEducativa getExperieciaEducativa() {
        return this.experieciaEducativa;
    }
    
    public void setExperieciaEducativa(ExperieciaEducativa experieciaEducativa) {
        this.experieciaEducativa = experieciaEducativa;
    }
    public Personal getPersonal() {
        return this.personal;
    }
    
    public void setPersonal(Personal personal) {
        this.personal = personal;
    }
    public String getPeriodo() {
        return this.periodo;
    }
    
    public void setPeriodo(String periodo) {
        this.periodo = periodo;
    }
    public String getTipoExamen() {
        return this.tipoExamen;
    }
    
    public void setTipoExamen(String tipoExamen) {
        this.tipoExamen = tipoExamen;
    }
    public Date getFechaCreacion() {
        return this.fechaCreacion;
    }
    
    public void setFechaCreacion(Date fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
    }
    public String getDescripcionExamen() {
        return this.descripcionExamen;
    }
    
    public void setDescripcionExamen(String descripcionExamen) {
        this.descripcionExamen = descripcionExamen;
    }
    public Integer getPorcTeoria() {
        return this.porcTeoria;
    }
    
    public void setPorcTeoria(Integer porcTeoria) {
        this.porcTeoria = porcTeoria;
    }
    public Integer getPorcPractica() {
        return this.porcPractica;
    }
    
    public void setPorcPractica(Integer porcPractica) {
        this.porcPractica = porcPractica;
    }
    public String getEstadoExamen() {
        return this.estadoExamen;
    }
    
    public void setEstadoExamen(String estadoExamen) {
        this.estadoExamen = estadoExamen;
    }
    public Set getExamenPreguntas() {
        return this.examenPreguntas;
    }
    
    public void setExamenPreguntas(Set examenPreguntas) {
        this.examenPreguntas = examenPreguntas;
    }




}


