package edu.uv.model.pojos;
// Generated 25/05/2014 11:11:21 AM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;
import org.hibernate.validator.constraints.Length;
import org.hibernate.validator.constraints.NotBlank;

/**
 * ExperieciaEducativa generated by hbm2java
 */
public class ExperieciaEducativa  implements java.io.Serializable {


     private Integer idExperieciaEducativa;
     private Academia academia;
     @NotBlank(message="Este campo no puede contener solo espacios en blanco")
     @Length(min=5, max=60, message="La longitud de campo no es valida, use de 5 a 60 caracteres")
     private String nombreEe;
     private Set unidadeses = new HashSet(0);
     private Set impartes = new HashSet(0);
     private Set examenesGeneradoses = new HashSet(0);

    public ExperieciaEducativa() {
    }

	
    public ExperieciaEducativa(Academia academia, String nombreEe) {
        this.academia = academia;
        this.nombreEe = nombreEe;
    }
    public ExperieciaEducativa(Academia academia, String nombreEe, Set unidadeses, Set impartes, Set examenesGeneradoses) {
       this.academia = academia;
       this.nombreEe = nombreEe;
       this.unidadeses = unidadeses;
       this.impartes = impartes;
       this.examenesGeneradoses = examenesGeneradoses;
    }
   
    public Integer getIdExperieciaEducativa() {
        return this.idExperieciaEducativa;
    }
    
    public void setIdExperieciaEducativa(Integer idExperieciaEducativa) {
        this.idExperieciaEducativa = idExperieciaEducativa;
    }
    public Academia getAcademia() {
        return this.academia;
    }
    
    public void setAcademia(Academia academia) {
        this.academia = academia;
    }
    public String getNombreEe() {
        return this.nombreEe;
    }
    
    public void setNombreEe(String nombreEe) {
        this.nombreEe = nombreEe;
    }
    public Set getUnidadeses() {
        return this.unidadeses;
    }
    
    public void setUnidadeses(Set unidadeses) {
        this.unidadeses = unidadeses;
    }
    public Set getImpartes() {
        return this.impartes;
    }
    
    public void setImpartes(Set impartes) {
        this.impartes = impartes;
    }
    public Set getExamenesGeneradoses() {
        return this.examenesGeneradoses;
    }
    
    public void setExamenesGeneradoses(Set examenesGeneradoses) {
        this.examenesGeneradoses = examenesGeneradoses;
    }




}


