package edu.uv.model.pojos;
// Generated 23/05/2014 05:30:57 PM by Hibernate Tools 3.6.0



/**
 * Imparte generated by hbm2java
 */
public class Imparte  implements java.io.Serializable {


     private Integer idImparte;
     private ExperieciaEducativa experieciaEducativa;
     private Personal personal;

    public Imparte() {
    }

    public Imparte(ExperieciaEducativa experieciaEducativa, Personal personal) {
       this.experieciaEducativa = experieciaEducativa;
       this.personal = personal;
    }
   
    public Integer getIdImparte() {
        return this.idImparte;
    }
    
    public void setIdImparte(Integer idImparte) {
        this.idImparte = idImparte;
    }
    public ExperieciaEducativa getExperieciaEducativa() {
        return this.experieciaEducativa;
    }
    
    public void setExperieciaEducativa(ExperieciaEducativa experieciaEducativa) {
        this.experieciaEducativa = experieciaEducativa;
    }
    public Personal getPersonal() {
        return this.personal;
    }
    
    public void setPersonal(Personal personal) {
        this.personal = personal;
    }




}


