package edu.uv.model.pojos;
// Generated 23/05/2014 05:30:57 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Personal generated by hbm2java
 */
public class Personal  implements java.io.Serializable {


     private Integer idPersonal;
     private Integer numeroPersonal;
     private String nombreProfesor;
     private Set academias = new HashSet(0);
     private Set usuarioses = new HashSet(0);
     private Set impartes = new HashSet(0);
     private Set examenesGeneradoses = new HashSet(0);

    public Personal() {
    }

	
    public Personal(String nombreProfesor) {
        this.nombreProfesor = nombreProfesor;
    }
    public Personal(Integer numeroPersonal, String nombreProfesor, Set academias, Set usuarioses, Set impartes, Set examenesGeneradoses) {
       this.numeroPersonal = numeroPersonal;
       this.nombreProfesor = nombreProfesor;
       this.academias = academias;
       this.usuarioses = usuarioses;
       this.impartes = impartes;
       this.examenesGeneradoses = examenesGeneradoses;
    }
   
    public Integer getIdPersonal() {
        return this.idPersonal;
    }
    
    public void setIdPersonal(Integer idPersonal) {
        this.idPersonal = idPersonal;
    }
    public Integer getNumeroPersonal() {
        return this.numeroPersonal;
    }
    
    public void setNumeroPersonal(Integer numeroPersonal) {
        this.numeroPersonal = numeroPersonal;
    }
    public String getNombreProfesor() {
        return this.nombreProfesor;
    }
    
    public void setNombreProfesor(String nombreProfesor) {
        this.nombreProfesor = nombreProfesor;
    }
    public Set getAcademias() {
        return this.academias;
    }
    
    public void setAcademias(Set academias) {
        this.academias = academias;
    }
    public Set getUsuarioses() {
        return this.usuarioses;
    }
    
    public void setUsuarioses(Set usuarioses) {
        this.usuarioses = usuarioses;
    }
    public Set getImpartes() {
        return this.impartes;
    }
    
    public void setImpartes(Set impartes) {
        this.impartes = impartes;
    }
    public Set getExamenesGeneradoses() {
        return this.examenesGeneradoses;
    }
    
    public void setExamenesGeneradoses(Set examenesGeneradoses) {
        this.examenesGeneradoses = examenesGeneradoses;
    }




}


