package edu.uv.model.pojos;
// Generated 25/05/2014 11:11:21 AM by Hibernate Tools 3.6.0

import org.hibernate.validator.constraints.Length;
import org.hibernate.validator.constraints.NotBlank;




/**
 * Respuestas generated by hbm2java
 */
public class Respuestas  implements java.io.Serializable {


     private Integer idRespuesta;
     private Pregunta pregunta;
     @NotBlank(message="Este campo no puede contener solo espacios en blanco")
     @Length(min=5, max=60, message="La longitud de campo no es valida, use de 5 a 60 caracteres")
     private String descripcionRespuesta;
     @NotBlank(message="Este campo no puede contener solo espacios en blanco")
     private String tipoResp;

    public Respuestas() {
    }

	
    public Respuestas(Pregunta pregunta) {
        this.pregunta = pregunta;
    }
    public Respuestas(Pregunta pregunta, String descripcionRespuesta, String tipoResp) {
       this.pregunta = pregunta;
       this.descripcionRespuesta = descripcionRespuesta;
       this.tipoResp = tipoResp;
    }
   
    public Integer getIdRespuesta() {
        return this.idRespuesta;
    }
    
    public void setIdRespuesta(Integer idRespuesta) {
        this.idRespuesta = idRespuesta;
    }
    public Pregunta getPregunta() {
        return this.pregunta;
    }
    
    public void setPregunta(Pregunta pregunta) {
        this.pregunta = pregunta;
    }
    public String getDescripcionRespuesta() {
        return this.descripcionRespuesta;
    }
    
    public void setDescripcionRespuesta(String descripcionRespuesta) {
        this.descripcionRespuesta = descripcionRespuesta;
    }
    public String getTipoResp() {
        return this.tipoResp;
    }
    
    public void setTipoResp(String tipoResp) {
        this.tipoResp = tipoResp;
    }




}


