package edu.uv.model.pojos;
// Generated 12/05/2014 09:41:03 AM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Roles generated by hbm2java
 */
public class Roles  implements java.io.Serializable {


     private Integer idRol;
     private String nombreRol;
     private String descripcionRol;
     private Set usuarioRols = new HashSet(0);

    public Roles() {
    }

	
    public Roles(String nombreRol) {
        this.nombreRol = nombreRol;
    }
    public Roles(String nombreRol, String descripcionRol, Set usuarioRols) {
       this.nombreRol = nombreRol;
       this.descripcionRol = descripcionRol;
       this.usuarioRols = usuarioRols;
    }
   
    public Integer getIdRol() {
        return this.idRol;
    }
    
    public void setIdRol(Integer idRol) {
        this.idRol = idRol;
    }
    public String getNombreRol() {
        return this.nombreRol;
    }
    
    public void setNombreRol(String nombreRol) {
        this.nombreRol = nombreRol;
    }
    public String getDescripcionRol() {
        return this.descripcionRol;
    }
    
    public void setDescripcionRol(String descripcionRol) {
        this.descripcionRol = descripcionRol;
    }
    public Set getUsuarioRols() {
        return this.usuarioRols;
    }
    
    public void setUsuarioRols(Set usuarioRols) {
        this.usuarioRols = usuarioRols;
    }




}


