package edu.uv.model.pojos;
// Generated 25/05/2014 11:11:21 AM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Unidades generated by hbm2java
 */
public class Unidades  implements java.io.Serializable {


     private Integer idUnidad;
     private ExperieciaEducativa experieciaEducativa;
     private String nombreUnidad;
     private Set temases = new HashSet(0);

    public Unidades() {
    }

	
    public Unidades(ExperieciaEducativa experieciaEducativa, String nombreUnidad) {
        this.experieciaEducativa = experieciaEducativa;
        this.nombreUnidad = nombreUnidad;
    }
    public Unidades(ExperieciaEducativa experieciaEducativa, String nombreUnidad, Set temases) {
       this.experieciaEducativa = experieciaEducativa;
       this.nombreUnidad = nombreUnidad;
       this.temases = temases;
    }
   
    public Integer getIdUnidad() {
        return this.idUnidad;
    }
    
    public void setIdUnidad(Integer idUnidad) {
        this.idUnidad = idUnidad;
    }
    public ExperieciaEducativa getExperieciaEducativa() {
        return this.experieciaEducativa;
    }
    
    public void setExperieciaEducativa(ExperieciaEducativa experieciaEducativa) {
        this.experieciaEducativa = experieciaEducativa;
    }
    public String getNombreUnidad() {
        return this.nombreUnidad;
    }
    
    public void setNombreUnidad(String nombreUnidad) {
        this.nombreUnidad = nombreUnidad;
    }
    public Set getTemases() {
        return this.temases;
    }
    
    public void setTemases(Set temases) {
        this.temases = temases;
    }




}


