package edu.uv.model.pojos;
// Generated 12/05/2014 09:41:03 AM by Hibernate Tools 3.6.0



/**
 * UsuarioRol generated by hbm2java
 */
public class UsuarioRol  implements java.io.Serializable {


     private Integer idUsuRol;
     private Usuarios usuarios;
     private Roles roles;

    public UsuarioRol() {
    }

    public UsuarioRol(Usuarios usuarios, Roles roles) {
       this.usuarios = usuarios;
       this.roles = roles;
    }
   
    public Integer getIdUsuRol() {
        return this.idUsuRol;
    }
    
    public void setIdUsuRol(Integer idUsuRol) {
        this.idUsuRol = idUsuRol;
    }
    public Usuarios getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Usuarios usuarios) {
        this.usuarios = usuarios;
    }
    public Roles getRoles() {
        return this.roles;
    }
    
    public void setRoles(Roles roles) {
        this.roles = roles;
    }




}


