package edu.uv.modelo.pojos;
// Generated 08/05/2014 12:06:02 AM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Academia generated by hbm2java
 */
public class Academia  implements java.io.Serializable {


     private Integer idAcademia;
     private Personal personal;
     private String nombreAcad;
     private Set carreras = new HashSet(0);
     private Set experieciaEducativas = new HashSet(0);

    public Academia() {
    }

	
    public Academia(Personal personal, String nombreAcad) {
        this.personal = personal;
        this.nombreAcad = nombreAcad;
    }
    public Academia(Personal personal, String nombreAcad, Set carreras, Set experieciaEducativas) {
       this.personal = personal;
       this.nombreAcad = nombreAcad;
       this.carreras = carreras;
       this.experieciaEducativas = experieciaEducativas;
    }
   
    public Integer getIdAcademia() {
        return this.idAcademia;
    }
    
    public void setIdAcademia(Integer idAcademia) {
        this.idAcademia = idAcademia;
    }
    public Personal getPersonal() {
        return this.personal;
    }
    
    public void setPersonal(Personal personal) {
        this.personal = personal;
    }
    public String getNombreAcad() {
        return this.nombreAcad;
    }
    
    public void setNombreAcad(String nombreAcad) {
        this.nombreAcad = nombreAcad;
    }
    public Set getCarreras() {
        return this.carreras;
    }
    
    public void setCarreras(Set carreras) {
        this.carreras = carreras;
    }
    public Set getExperieciaEducativas() {
        return this.experieciaEducativas;
    }
    
    public void setExperieciaEducativas(Set experieciaEducativas) {
        this.experieciaEducativas = experieciaEducativas;
    }




}


