package edu.uv.modelo.pojos;
// Generated 08/05/2014 12:06:02 AM by Hibernate Tools 3.6.0



/**
 * ExamenesGeneradosHasPreguntaId generated by hbm2java
 */
public class ExamenesGeneradosHasPreguntaId  implements java.io.Serializable {


     private int examenesGeneradosIdexamenesGenerados;
     private int preguntaIdPregunta;

    public ExamenesGeneradosHasPreguntaId() {
    }

    public ExamenesGeneradosHasPreguntaId(int examenesGeneradosIdexamenesGenerados, int preguntaIdPregunta) {
       this.examenesGeneradosIdexamenesGenerados = examenesGeneradosIdexamenesGenerados;
       this.preguntaIdPregunta = preguntaIdPregunta;
    }
   
    public int getExamenesGeneradosIdexamenesGenerados() {
        return this.examenesGeneradosIdexamenesGenerados;
    }
    
    public void setExamenesGeneradosIdexamenesGenerados(int examenesGeneradosIdexamenesGenerados) {
        this.examenesGeneradosIdexamenesGenerados = examenesGeneradosIdexamenesGenerados;
    }
    public int getPreguntaIdPregunta() {
        return this.preguntaIdPregunta;
    }
    
    public void setPreguntaIdPregunta(int preguntaIdPregunta) {
        this.preguntaIdPregunta = preguntaIdPregunta;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ExamenesGeneradosHasPreguntaId) ) return false;
		 ExamenesGeneradosHasPreguntaId castOther = ( ExamenesGeneradosHasPreguntaId ) other; 
         
		 return (this.getExamenesGeneradosIdexamenesGenerados()==castOther.getExamenesGeneradosIdexamenesGenerados())
 && (this.getPreguntaIdPregunta()==castOther.getPreguntaIdPregunta());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getExamenesGeneradosIdexamenesGenerados();
         result = 37 * result + this.getPreguntaIdPregunta();
         return result;
   }   


}


