package edu.uv.modelo.pojos;
// Generated 08/05/2014 12:06:02 AM by Hibernate Tools 3.6.0



/**
 * ExamenesGeneradosHasPregunta generated by hbm2java
 */
public class ExamenesGeneradosHasPregunta  implements java.io.Serializable {


     private ExamenesGeneradosHasPreguntaId id;
     private ExamenesGenerados examenesGenerados;
     private Pregunta pregunta;
     private Integer puntaje;

    public ExamenesGeneradosHasPregunta() {
    }

	
    public ExamenesGeneradosHasPregunta(ExamenesGeneradosHasPreguntaId id, ExamenesGenerados examenesGenerados, Pregunta pregunta) {
        this.id = id;
        this.examenesGenerados = examenesGenerados;
        this.pregunta = pregunta;
    }
    public ExamenesGeneradosHasPregunta(ExamenesGeneradosHasPreguntaId id, ExamenesGenerados examenesGenerados, Pregunta pregunta, Integer puntaje) {
       this.id = id;
       this.examenesGenerados = examenesGenerados;
       this.pregunta = pregunta;
       this.puntaje = puntaje;
    }
   
    public ExamenesGeneradosHasPreguntaId getId() {
        return this.id;
    }
    
    public void setId(ExamenesGeneradosHasPreguntaId id) {
        this.id = id;
    }
    public ExamenesGenerados getExamenesGenerados() {
        return this.examenesGenerados;
    }
    
    public void setExamenesGenerados(ExamenesGenerados examenesGenerados) {
        this.examenesGenerados = examenesGenerados;
    }
    public Pregunta getPregunta() {
        return this.pregunta;
    }
    
    public void setPregunta(Pregunta pregunta) {
        this.pregunta = pregunta;
    }
    public Integer getPuntaje() {
        return this.puntaje;
    }
    
    public void setPuntaje(Integer puntaje) {
        this.puntaje = puntaje;
    }




}


