package edu.uv.modelo.pojos;
// Generated 08/05/2014 12:06:02 AM by Hibernate Tools 3.6.0


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * ExamenesGenerados generated by hbm2java
 */
public class ExamenesGenerados  implements java.io.Serializable {


     private Integer idexamenesGenerados;
     private Personal personal;
     private int periodo;
     private String tipoExam;
     private Date fechaCreacion;
     private String descripcion;
     private Integer porcTeoria;
     private Integer porcPractica;
     private String estado;
     private Set examenesGeneradosHasPreguntas = new HashSet(0);

    public ExamenesGenerados() {
    }

	
    public ExamenesGenerados(Personal personal, int periodo, String tipoExam, Date fechaCreacion, String estado) {
        this.personal = personal;
        this.periodo = periodo;
        this.tipoExam = tipoExam;
        this.fechaCreacion = fechaCreacion;
        this.estado = estado;
    }
    public ExamenesGenerados(Personal personal, int periodo, String tipoExam, Date fechaCreacion, String descripcion, Integer porcTeoria, Integer porcPractica, String estado, Set examenesGeneradosHasPreguntas) {
       this.personal = personal;
       this.periodo = periodo;
       this.tipoExam = tipoExam;
       this.fechaCreacion = fechaCreacion;
       this.descripcion = descripcion;
       this.porcTeoria = porcTeoria;
       this.porcPractica = porcPractica;
       this.estado = estado;
       this.examenesGeneradosHasPreguntas = examenesGeneradosHasPreguntas;
    }
   
    public Integer getIdexamenesGenerados() {
        return this.idexamenesGenerados;
    }
    
    public void setIdexamenesGenerados(Integer idexamenesGenerados) {
        this.idexamenesGenerados = idexamenesGenerados;
    }
    public Personal getPersonal() {
        return this.personal;
    }
    
    public void setPersonal(Personal personal) {
        this.personal = personal;
    }
    public int getPeriodo() {
        return this.periodo;
    }
    
    public void setPeriodo(int periodo) {
        this.periodo = periodo;
    }
    public String getTipoExam() {
        return this.tipoExam;
    }
    
    public void setTipoExam(String tipoExam) {
        this.tipoExam = tipoExam;
    }
    public Date getFechaCreacion() {
        return this.fechaCreacion;
    }
    
    public void setFechaCreacion(Date fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Integer getPorcTeoria() {
        return this.porcTeoria;
    }
    
    public void setPorcTeoria(Integer porcTeoria) {
        this.porcTeoria = porcTeoria;
    }
    public Integer getPorcPractica() {
        return this.porcPractica;
    }
    
    public void setPorcPractica(Integer porcPractica) {
        this.porcPractica = porcPractica;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    public Set getExamenesGeneradosHasPreguntas() {
        return this.examenesGeneradosHasPreguntas;
    }
    
    public void setExamenesGeneradosHasPreguntas(Set examenesGeneradosHasPreguntas) {
        this.examenesGeneradosHasPreguntas = examenesGeneradosHasPreguntas;
    }




}


