package edu.uv.modelo.pojos;
// Generated 08/05/2014 12:06:02 AM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * ExperieciaEducativa generated by hbm2java
 */
public class ExperieciaEducativa  implements java.io.Serializable {


     private Integer idExperieciaEducativa;
     private Academia academia;
     private String nombreEe;
     private Set unidadeses = new HashSet(0);
     private Set personals = new HashSet(0);

    public ExperieciaEducativa() {
    }

	
    public ExperieciaEducativa(Academia academia, String nombreEe) {
        this.academia = academia;
        this.nombreEe = nombreEe;
    }
    public ExperieciaEducativa(Academia academia, String nombreEe, Set unidadeses, Set personals) {
       this.academia = academia;
       this.nombreEe = nombreEe;
       this.unidadeses = unidadeses;
       this.personals = personals;
    }
   
    public Integer getIdExperieciaEducativa() {
        return this.idExperieciaEducativa;
    }
    
    public void setIdExperieciaEducativa(Integer idExperieciaEducativa) {
        this.idExperieciaEducativa = idExperieciaEducativa;
    }
    public Academia getAcademia() {
        return this.academia;
    }
    
    public void setAcademia(Academia academia) {
        this.academia = academia;
    }
    public String getNombreEe() {
        return this.nombreEe;
    }
    
    public void setNombreEe(String nombreEe) {
        this.nombreEe = nombreEe;
    }
    public Set getUnidadeses() {
        return this.unidadeses;
    }
    
    public void setUnidadeses(Set unidadeses) {
        this.unidadeses = unidadeses;
    }
    public Set getPersonals() {
        return this.personals;
    }
    
    public void setPersonals(Set personals) {
        this.personals = personals;
    }




}


