package edu.uv.modelo.pojos;
// Generated 08/05/2014 12:06:02 AM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Personal generated by hbm2java
 */
public class Personal  implements java.io.Serializable {


     private int numeroPersonal;
     private String nombre;
     private Set usuarioses = new HashSet(0);
     private Set academias = new HashSet(0);
     private Set experieciaEducativas = new HashSet(0);
     private Set examenesGeneradoses = new HashSet(0);

    public Personal() {
    }

	
    public Personal(int numeroPersonal, String nombre) {
        this.numeroPersonal = numeroPersonal;
        this.nombre = nombre;
    }
    public Personal(int numeroPersonal, String nombre, Set usuarioses, Set academias, Set experieciaEducativas, Set examenesGeneradoses) {
       this.numeroPersonal = numeroPersonal;
       this.nombre = nombre;
       this.usuarioses = usuarioses;
       this.academias = academias;
       this.experieciaEducativas = experieciaEducativas;
       this.examenesGeneradoses = examenesGeneradoses;
    }
   
    public int getNumeroPersonal() {
        return this.numeroPersonal;
    }
    
    public void setNumeroPersonal(int numeroPersonal) {
        this.numeroPersonal = numeroPersonal;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Set getUsuarioses() {
        return this.usuarioses;
    }
    
    public void setUsuarioses(Set usuarioses) {
        this.usuarioses = usuarioses;
    }
    public Set getAcademias() {
        return this.academias;
    }
    
    public void setAcademias(Set academias) {
        this.academias = academias;
    }
    public Set getExperieciaEducativas() {
        return this.experieciaEducativas;
    }
    
    public void setExperieciaEducativas(Set experieciaEducativas) {
        this.experieciaEducativas = experieciaEducativas;
    }
    public Set getExamenesGeneradoses() {
        return this.examenesGeneradoses;
    }
    
    public void setExamenesGeneradoses(Set examenesGeneradoses) {
        this.examenesGeneradoses = examenesGeneradoses;
    }




}


