package edu.uv.modelo.pojos;
// Generated 08/05/2014 12:06:02 AM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Pregunta generated by hbm2java
 */
public class Pregunta  implements java.io.Serializable {


     private Integer idPregunta;
     private Temas temas;
     private String tipo;
     private String descripcion;
     private String modalidad;
     private int complejidad;
     private Integer puntuacion;
     private String comentRetroalimentacion;
     private Set examenesGeneradosHasPreguntas = new HashSet(0);
     private Set respuestases = new HashSet(0);

    public Pregunta() {
    }

	
    public Pregunta(Temas temas, String tipo, String descripcion, String modalidad, int complejidad) {
        this.temas = temas;
        this.tipo = tipo;
        this.descripcion = descripcion;
        this.modalidad = modalidad;
        this.complejidad = complejidad;
    }
    public Pregunta(Temas temas, String tipo, String descripcion, String modalidad, int complejidad, Integer puntuacion, String comentRetroalimentacion, Set examenesGeneradosHasPreguntas, Set respuestases) {
       this.temas = temas;
       this.tipo = tipo;
       this.descripcion = descripcion;
       this.modalidad = modalidad;
       this.complejidad = complejidad;
       this.puntuacion = puntuacion;
       this.comentRetroalimentacion = comentRetroalimentacion;
       this.examenesGeneradosHasPreguntas = examenesGeneradosHasPreguntas;
       this.respuestases = respuestases;
    }
   
    public Integer getIdPregunta() {
        return this.idPregunta;
    }
    
    public void setIdPregunta(Integer idPregunta) {
        this.idPregunta = idPregunta;
    }
    public Temas getTemas() {
        return this.temas;
    }
    
    public void setTemas(Temas temas) {
        this.temas = temas;
    }
    public String getTipo() {
        return this.tipo;
    }
    
    public void setTipo(String tipo) {
        this.tipo = tipo;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public String getModalidad() {
        return this.modalidad;
    }
    
    public void setModalidad(String modalidad) {
        this.modalidad = modalidad;
    }
    public int getComplejidad() {
        return this.complejidad;
    }
    
    public void setComplejidad(int complejidad) {
        this.complejidad = complejidad;
    }
    public Integer getPuntuacion() {
        return this.puntuacion;
    }
    
    public void setPuntuacion(Integer puntuacion) {
        this.puntuacion = puntuacion;
    }
    public String getComentRetroalimentacion() {
        return this.comentRetroalimentacion;
    }
    
    public void setComentRetroalimentacion(String comentRetroalimentacion) {
        this.comentRetroalimentacion = comentRetroalimentacion;
    }
    public Set getExamenesGeneradosHasPreguntas() {
        return this.examenesGeneradosHasPreguntas;
    }
    
    public void setExamenesGeneradosHasPreguntas(Set examenesGeneradosHasPreguntas) {
        this.examenesGeneradosHasPreguntas = examenesGeneradosHasPreguntas;
    }
    public Set getRespuestases() {
        return this.respuestases;
    }
    
    public void setRespuestases(Set respuestases) {
        this.respuestases = respuestases;
    }




}


