package edu.uv.modelo.pojos;
// Generated 08/05/2014 12:06:02 AM by Hibernate Tools 3.6.0



/**
 * Respuestas generated by hbm2java
 */
public class Respuestas  implements java.io.Serializable {


     private Integer idRespuestas;
     private Pregunta pregunta;
     private String descripcionRespuesta;
     private String tipoResp;

    public Respuestas() {
    }

	
    public Respuestas(Pregunta pregunta) {
        this.pregunta = pregunta;
    }
    public Respuestas(Pregunta pregunta, String descripcionRespuesta, String tipoResp) {
       this.pregunta = pregunta;
       this.descripcionRespuesta = descripcionRespuesta;
       this.tipoResp = tipoResp;
    }
   
    public Integer getIdRespuestas() {
        return this.idRespuestas;
    }
    
    public void setIdRespuestas(Integer idRespuestas) {
        this.idRespuestas = idRespuestas;
    }
    public Pregunta getPregunta() {
        return this.pregunta;
    }
    
    public void setPregunta(Pregunta pregunta) {
        this.pregunta = pregunta;
    }
    public String getDescripcionRespuesta() {
        return this.descripcionRespuesta;
    }
    
    public void setDescripcionRespuesta(String descripcionRespuesta) {
        this.descripcionRespuesta = descripcionRespuesta;
    }
    public String getTipoResp() {
        return this.tipoResp;
    }
    
    public void setTipoResp(String tipoResp) {
        this.tipoResp = tipoResp;
    }




}


