package edu.uv.modelo.pojos;
// Generated 08/05/2014 12:06:02 AM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Temas generated by hbm2java
 */
public class Temas  implements java.io.Serializable {


     private Integer idtemas;
     private Unidades unidades;
     private Temas temas;
     private String nombre;
     private Set temases = new HashSet(0);
     private Set preguntas = new HashSet(0);

    public Temas() {
    }

	
    public Temas(Unidades unidades, Temas temas, String nombre) {
        this.unidades = unidades;
        this.temas = temas;
        this.nombre = nombre;
    }
    public Temas(Unidades unidades, Temas temas, String nombre, Set temases, Set preguntas) {
       this.unidades = unidades;
       this.temas = temas;
       this.nombre = nombre;
       this.temases = temases;
       this.preguntas = preguntas;
    }
   
    public Integer getIdtemas() {
        return this.idtemas;
    }
    
    public void setIdtemas(Integer idtemas) {
        this.idtemas = idtemas;
    }
    public Unidades getUnidades() {
        return this.unidades;
    }
    
    public void setUnidades(Unidades unidades) {
        this.unidades = unidades;
    }
    public Temas getTemas() {
        return this.temas;
    }
    
    public void setTemas(Temas temas) {
        this.temas = temas;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Set getTemases() {
        return this.temases;
    }
    
    public void setTemases(Set temases) {
        this.temases = temases;
    }
    public Set getPreguntas() {
        return this.preguntas;
    }
    
    public void setPreguntas(Set preguntas) {
        this.preguntas = preguntas;
    }




}


