package edu.uv.modelo.pojos;
// Generated 08/05/2014 12:06:02 AM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Unidades generated by hbm2java
 */
public class Unidades  implements java.io.Serializable {


     private Integer idUnidades;
     private ExperieciaEducativa experieciaEducativa;
     private String nombre;
     private Set temases = new HashSet(0);

    public Unidades() {
    }

	
    public Unidades(ExperieciaEducativa experieciaEducativa, String nombre) {
        this.experieciaEducativa = experieciaEducativa;
        this.nombre = nombre;
    }
    public Unidades(ExperieciaEducativa experieciaEducativa, String nombre, Set temases) {
       this.experieciaEducativa = experieciaEducativa;
       this.nombre = nombre;
       this.temases = temases;
    }
   
    public Integer getIdUnidades() {
        return this.idUnidades;
    }
    
    public void setIdUnidades(Integer idUnidades) {
        this.idUnidades = idUnidades;
    }
    public ExperieciaEducativa getExperieciaEducativa() {
        return this.experieciaEducativa;
    }
    
    public void setExperieciaEducativa(ExperieciaEducativa experieciaEducativa) {
        this.experieciaEducativa = experieciaEducativa;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Set getTemases() {
        return this.temases;
    }
    
    public void setTemases(Set temases) {
        this.temases = temases;
    }




}


